const lightPlanPhases = [
  {
    key: "phase1",
    name: "Phase 1 (Weeks 1-4)",
    days: 28,
    weeks: 4,
    goal: "Awareness, Trigger Identification, and Initial Reduction",
    strategies: [
      "Keep a smoking diary to track cigarettes, triggers, and mood.",
      "Identify top 3 smoking triggers.",
      "Note alternative activities for triggers.",
      "Substitute 1 cigarette per day with a healthy alternative.",
      "Introduce nicotine gum/lozenges (if desired) to manage cravings.",
      "Change your routine to avoid triggers.",
      "Practice mindful breathing exercises.",
      "Reward yourself for progress.",
    ],
  },
  {
    key: "phase2",
    name: "Phase 2 (Weeks 5-8)",
    days: 28,
    weeks: 4,
    goal: "Gradual Reduction and Management",
    strategies: [
      "Delay your first cigarette of the day.",
      "Extend the time between cigarettes.",
      "Focus on eliminating a cigarette associated with a specific trigger.",
      "Increase the delay between each cigarette.",
      "Practice visualization techniques to mentally distance yourself from cravings.",
      "Review your smoking diary and identify remaining challenges.",
      "Refine your coping mechanisms and alternative activities.",
      "Reward yourself for completing Phase 2.",
    ],
  },
  {
    key: "phase3",
    name: "Phase 3 (Weeks 9-12)",
    days: 28,
    weeks: 4,
    goal: "Stabilization and Maintenance",
    strategies: [
      "Work to remove one more cigarette.",
      "Introduce more healthy lifestyle choices like regular physical activity.",
      "Continue to focus on the habits you've broken so far.",
      "Continue to focus on avoiding high risk scenarios.",
      "Stay focused on the reasons why you started the plan.",
      "Identify high-risk situations and develop plans for managing them.",
      "Continue practicing your coping mechanisms and alternative activities.",
    ],
  },
]

const moderatePlanPhases = [
  {
    key: "phase1",
    name: "Phase 1 (Weeks 1–4)",
    days: 28,
    weeks: 4,
    goal: "Awareness and Trigger Pattern Recognition",
    strategies: [
      "Keep a detailed smoking diary (time, trigger, mood, location).",
      "Identify top 5 triggers and rate each on difficulty to manage.",
      "Substitute 1–2 cigarettes per day with a healthier action.",
      "Introduce short physical activity (e.g., walk, stretching) when craving hits.",
      "Start using nicotine replacement (gum, patch, lozenge) if needed.",
      "Begin reducing cigarettes in high-control situations (e.g., home).",
      "Practice daily deep breathing exercises (3–5 minutes).",
      "Write your reasons for quitting and review daily.",
    ],
  },
  {
    key: "phase2",
    name: "Phase 2 (Weeks 5–8)",
    days: 28,
    weeks: 4,
    goal: "Consistent Reduction and Habit Shifting",
    strategies: [
      "Reduce daily smoking by 25–30%.",
      "Eliminate smoking in 1 environment (e.g., car or work breaks).",
      "Switch to low-nicotine or filtered cigarettes for some smokes.",
      "Set smoke-free time zones (e.g., 8am–12pm).",
      "Increase physical activity to reduce stress.",
      "Replace evening smoke with a relaxing ritual (e.g., tea, journaling).",
      "Track cravings and coping success rate.",
      "Reward yourself weekly for reduced cigarette count.",
    ],
  },
  {
    key: "phase3",
    name: "Phase 3 (Weeks 9–12)",
    days: 28,
    weeks: 4,
    goal: "Low Use & Craving Mastery",
    strategies: [
      "Reduce smoking to <5 cigarettes/day.",
      "Practice total abstinence 1–2 days/week (trial run).",
      "Strengthen mental visualization of a smoke-free identity.",
      "Use positive affirmations or mantras.",
      "Stay away from known high-risk smoking environments.",
      "Prepare for and rehearse how to respond to social smoking situations.",
      "Increase healthy substitutions (snacks, hobbies).",
      "Evaluate and celebrate progress.",
    ],
  },
  
]

const heavyPlanPhases = [
  {
    key: "phase1",
    name: "Phase 1 (Weeks 1–4)",
    days: 28,
    weeks: 4,
    goal: "Data Collection, Awareness, and Support Setup",
    strategies: [
      "Track every cigarette (when, where, why).",
      "Join a support group or tell 2 trusted people your goal.",
      "Consult doctor/pharmacist about nicotine replacement options.",
      "Substitute 2–3 cigarettes/day with an activity (walk, gum, breathwork).",
      "Delay your first cigarette each morning by 30 minutes.",
      "Begin a stress-reduction activity (yoga, journaling, or meditation).",
      "List and rank your top 5 smoking triggers.",
      "Choose 1 cigarette daily to remove from your routine.",
    ],
  },
  {
    key: "phase2",
    name: "Phase 2 (Weeks 5–8)",
    days: 28,
    weeks: 4,
    goal: "Structured Reduction and Craving Mastery",
    strategies: [
      "Cut cigarette use by 25–30%.",
      "Replace 1 smoking break with exercise.",
      "Switch to low-nicotine alternatives for some cigarettes.",
      "Use nicotine patches/gum consistently.",
      "Avoid caffeine/alcohol if they are smoking triggers.",
      "Practice urge-surfing: ride out cravings for 5–10 minutes.",
      "Continue building your support network.",
      "Develop and post a visible daily plan to stay smoke-free in certain periods.",
    ],
  },
  {
    key: "phase3",
    name: "Phase 3 (Weeks 9–12)",
    days: 28,
    weeks: 4,
    goal: "Pre-Quit Stabilization",
    strategies: [
      "Aim for <10 cigarettes/day by end of this phase.",
      "Increase your non-smoking hours daily.",
      "Do 1 smoke-free trial day/week — full abstinence.",
      "Start tapering off nicotine replacement if desired.",
      "Handle urges by doing: 1) Delay, 2) Distract, 3) Deep breathe, 4) Drink water.",
      "Plan your 'quit day' by end of week 12.",
      "Log what’s hardest — prepare targeted responses.",
      "Reflect on mental, physical, and financial benefits so far.",
    ],
  },
  
]

export { lightPlanPhases, moderatePlanPhases, heavyPlanPhases }
