export const freePlanPhases = [
  {
    key: "phase1",
    name: "Phase 1 (Weeks 1-4)",
    days: 28,
    weeks: 4,
    goal: "Awareness, Trigger Identification, and Initial Reduction",
    strategies: [
      "Keep a smoking diary to track cigarettes, triggers, and mood.",
      "Identify top 3 smoking triggers.",
      "Note alternative activities for triggers.",
      "Substitute 1 cigarette per day with a healthy alternative.",
      "Introduce nicotine gum/lozenges (if desired) to manage cravings.",
      "Change your routine to avoid triggers.",
      "Practice mindful breathing exercises.",
      "Reward yourself for progress.",
    ],
  },
  {
    key: "phase2",
    name: "Phase 2 (Weeks 5-8)",
    days: 28,
    weeks: 4,
    goal: "Gradual Reduction and Management",
    strategies: [
      "Delay your first cigarette of the day.",
      "Extend the time between cigarettes.",
      "Focus on eliminating a cigarette associated with a specific trigger.",
      "Increase the delay between each cigarette.",
      "Practice visualization techniques to mentally distance yourself from cravings.",
      "Review your smoking diary and identify remaining challenges.",
      "Refine your coping mechanisms and alternative activities.",
      "Reward yourself for completing Phase 2.",
    ],
  },
  {
    key: "phase3",
    name: "Phase 3 (Weeks 9-12)",
    days: 28,
    weeks: 4,
    goal: "Stabilization and Maintenance",
    strategies: [
      "Work to remove one more cigarette.",
      "Introduce more healthy lifestyle choices like regular physical activity.",
      "Continue to focus on the habits you've broken so far.",
      "Continue to focus on avoiding high risk scenarios.",
      "Stay focused on the reasons why you started the plan.",
      "Identify high-risk situations and develop plans for managing them.",
      "Continue practicing your coping mechanisms and alternative activities.",
    ],
  },
]